#Sample Dockerfile for NodeJS Apps
FROM node:20
ENV NODE_ENV=production
WORKDIR /app
COPY ["package*.json", "package-lock.json*", "./"]
RUN npm install --production
COPY . .
EXPOSE 3000

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont

# Install Puppeteer (and other dependencies)
COPY package*.json ./
RUN npm install

# Install Puppeteer and its dependencies
RUN npx puppeteer browsers install chrome

# Expose any necessary ports
# ...

# Run your application
CMD [ "node", "index.js" ]
